// src/redux/constants/courseConstants.js
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS';
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL';

export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS';
export const COURSE_DETAILS_FAIL = 'COURSE_DETAILS_FAIL';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const COURSE_FILTERED_SUCCESS = 'COURSE_FILTERED_SUCCESS';
export const CLEAR_COURSES = 'CLEAR_COURSES';

export const COURSE_ENROLL_FAIL='COURSE_ENROLL_FAIL';
export const FETCH_COURSES_SUCCESS='FETCH_COURSES_SUCCESS';
export const COURSE_ENROLL_SUCCESS='COURSE_ENROLL_SUCCESS';
export const FETCH_COURSES_FAIL='FETCH_COURSES_FAIL';
export const COURSE_COMPLETE_SUCCESS='COURSE_COMPLETE_SUCCESS';
export const COURSE_COMPLETE_FAIL='COURSE_COMPLETE_FAIL';
